export interface ThemeVisualConfig {
  slug: string
  primary: string
  accent: string
  heroStart: string
  heroEnd: string
  pageBackground: string
  cardBackground: string
  cardAltBackground: string
  highlightBackground: string
  highlightAltBackground: string
  text: string
  subtext: string
  tagBackground: string
  tagText: string
  gradientStart: string
  gradientEnd: string
  previewStart: string
  previewEnd: string
  borderColor: string
}

const defaultConfig: ThemeVisualConfig = {
  slug: 'default',
  primary: '#1890ff',
  accent: '#722ed1',
  heroStart: '#f9fbff',
  heroEnd: '#ffffff',
  pageBackground: '#f4f7ff',
  cardBackground: '#ffffff',
  cardAltBackground: '#f7f9fc',
  highlightBackground: '#fffbe6',
  highlightAltBackground: '#f6ffed',
  text: '#0f172a',
  subtext: '#475569',
  tagBackground: '#1890ff',
  tagText: '#ffffff',
  gradientStart: '#1890ff',
  gradientEnd: '#722ed1',
  previewStart: '#80bfff',
  previewEnd: '#a78bfa',
  borderColor: '#e5e7eb',
}

const themeConfigs: Record<string, ThemeVisualConfig> = {
  default: defaultConfig,
  dark: {
    slug: 'dark',
    primary: '#ff6b35',
    accent: '#f7931e',
    heroStart: '#1a1a1a',
    heroEnd: '#2c2c2c',
    pageBackground: '#1a1a1a',
    cardBackground: '#2c2c2c',
    cardAltBackground: '#333333',
    highlightBackground: '#333333',
    highlightAltBackground: '#2c2c2c',
    text: '#ffffff',
    subtext: '#999999',
    tagBackground: '#ff6b35',
    tagText: '#ffffff',
    gradientStart: '#ff6b35',
    gradientEnd: '#f7931e',
    previewStart: '#ff6b35',
    previewEnd: '#f7931e',
    borderColor: '#333333',
  },
  minimal: {
    slug: 'minimal',
    primary: '#0ea5e9',
    accent: '#22c55e',
    heroStart: '#ffffff',
    heroEnd: '#f8fafc',
    pageBackground: '#ffffff',
    cardBackground: '#ffffff',
    cardAltBackground: '#f9fafb',
    highlightBackground: '#eef2ff',
    highlightAltBackground: '#ecfccb',
    text: '#111827',
    subtext: '#6b7280',
    tagBackground: '#0ea5e9',
    tagText: '#ffffff',
    gradientStart: '#0ea5e9',
    gradientEnd: '#22c55e',
    previewStart: '#bae6fd',
    previewEnd: '#86efac',
    borderColor: '#e5e7eb',
  },
  magazine: {
    slug: 'magazine',
    primary: '#dc2626',
    accent: '#ea580c',
    heroStart: '#fef2f2',
    heroEnd: '#ffffff',
    pageBackground: '#fafafa',
    cardBackground: '#ffffff',
    cardAltBackground: '#f5f5f5',
    highlightBackground: '#fef2f2',
    highlightAltBackground: '#fff7ed',
    text: '#1f2937',
    subtext: '#6b7280',
    tagBackground: '#dc2626',
    tagText: '#ffffff',
    gradientStart: '#dc2626',
    gradientEnd: '#ea580c',
    previewStart: '#fca5a5',
    previewEnd: '#fdba74',
    borderColor: '#e5e7eb',
  },
  card: {
    slug: 'card',
    primary: '#8b5cf6',
    accent: '#ec4899',
    heroStart: '#faf5ff',
    heroEnd: '#ffffff',
    pageBackground: '#f9fafb',
    cardBackground: '#ffffff',
    cardAltBackground: '#f3f4f6',
    highlightBackground: '#faf5ff',
    highlightAltBackground: '#fdf2f8',
    text: '#1f2937',
    subtext: '#6b7280',
    tagBackground: '#8b5cf6',
    tagText: '#ffffff',
    gradientStart: '#8b5cf6',
    gradientEnd: '#ec4899',
    previewStart: '#c4b5fd',
    previewEnd: '#f9a8d4',
    borderColor: '#e5e7eb',
  },
  'bootstrap-blog': {
    slug: 'bootstrap-blog',
    primary: '#000000',
    accent: '#333333',
    heroStart: '#ffffff',
    heroEnd: '#f9fafb',
    pageBackground: '#ffffff',
    cardBackground: '#ffffff',
    cardAltBackground: '#f9fafb',
    highlightBackground: '#f9fafb',
    highlightAltBackground: '#ffffff',
    text: '#000000',
    subtext: '#666666',
    tagBackground: '#000000',
    tagText: '#ffffff',
    gradientStart: '#000000',
    gradientEnd: '#333333',
    previewStart: '#666666',
    previewEnd: '#999999',
    borderColor: '#e5e7eb',
  },
  comprehensive: {
    slug: 'comprehensive',
    primary: '#1890ff',
    accent: '#52c41a',
    heroStart: '#f0f9ff',
    heroEnd: '#ffffff',
    pageBackground: '#fafafa',
    cardBackground: '#ffffff',
    cardAltBackground: '#f5f5f5',
    highlightBackground: '#e6f7ff',
    highlightAltBackground: '#f6ffed',
    text: '#262626',
    subtext: '#8c8c8c',
    tagBackground: '#1890ff',
    tagText: '#ffffff',
    gradientStart: '#1890ff',
    gradientEnd: '#52c41a',
    previewStart: '#91d5ff',
    previewEnd: '#b7eb8f',
    borderColor: '#d9d9d9',
  },
  'magazine-multi': {
    slug: 'magazine-multi',
    primary: '#dc2626',
    accent: '#991b1b',
    heroStart: '#ffffff',
    heroEnd: '#f9fafb',
    pageBackground: '#ffffff',
    cardBackground: '#ffffff',
    cardAltBackground: '#f5f5f5',
    highlightBackground: '#fef2f2',
    highlightAltBackground: '#fee2e2',
    text: '#1f2937',
    subtext: '#6b7280',
    tagBackground: '#dc2626',
    tagText: '#ffffff',
    gradientStart: '#dc2626',
    gradientEnd: '#991b1b',
    previewStart: '#fca5a5',
    previewEnd: '#ef4444',
    borderColor: '#e5e7eb',
  },
  'minimal-lifestyle': {
    slug: 'minimal-lifestyle',
    primary: '#d4a574',
    accent: '#c49564',
    heroStart: '#f5f3f0',
    heroEnd: '#faf9f7',
    pageBackground: '#faf9f7',
    cardBackground: '#ffffff',
    cardAltBackground: '#f5f3f0',
    highlightBackground: '#f5f3f0',
    highlightAltBackground: '#ffffff',
    text: '#2c2c2c',
    subtext: '#666666',
    tagBackground: '#f5f3f0',
    tagText: '#d4a574',
    gradientStart: '#d4a574',
    gradientEnd: '#c49564',
    previewStart: '#d4a574',
    previewEnd: '#c49564',
    borderColor: '#e8e5e0',
  },
}

export function getThemeConfig(slug?: string): ThemeVisualConfig {
  if (!slug) return defaultConfig
  return themeConfigs[slug] || defaultConfig
}


